Repository Abdalrhman7mida/accessories-agency-website, pull requests merged in 2022-12, with the labels that each got.

#6 Frontend-feat-5-imp_home
  css/style.css
  index.html
Labels: enhancement, frontend, 4h

#8 Frontend-feat-7-imp about
  css/style.css
  index.html
Labels: enhancement, frontend, 2h

#10 Frontend-feat-9-implement_portfolio_section
  css/style.css
  index.html
Labels: frontend, 2h
